### ISSUE TITLE
it does not work in android n

### ISSUE THREAD

**Issue by wajdidhc** [MeetMe/PaletteBar#1]
i tried it in an any android and it worked but in android n it didnt work

**Comment by briandherbert** [comment]
Thanks, I haven't tried it with N yet, will take a look.

**Comment by wajdidhc** [comment]
can you please fix it asap

**Comment by Kennyc1012** [comment]
What isn't working about it? It currently is working inside of the MeetMe app running the latest N developer preview (5). If there is a crash, can you please post a crash log.

**Comment by wajdidhc** [comment]
thanks it is know working before when i choose any color it appeared like i select blue 
know everything works
