### ISSUE TITLE
Implementation Example Required

### ISSUE THREAD

**Issue by tanishqsatsangi** [MeetMe/PaletteBar#3]
Please provide a sample how to implement it in the code as well as how can i remove the border color changing i don't want it .

**Comment by jimmithy** [comment]
You can add the PaletteBar view to your xml layout like so 

```
 <com.meetme.android.palettebar.PaletteBar
        android:id="@+id/paletteBar"
        android:layout_width="match_parent"
        android:layout_height="40dp" />
```

Then in your class you can attach a listener to be notified on the colour change

```
PaletteBar paletteBar = findViewById(R.id.paletteBar);
paletteBar.setListener(new PaletteBarListener() {
    @Override
    public void onColorSelected(@ColorInt int colorInt) {
        // Use the selected color
    }
});
```

To remove the border color, you can adjust the variable `mShowColorInMargin` in `PaletteBar.java` to false, or call `setColorMarginPx` with the value 0.

**Comment by jimmithy** [comment]
A usage example has now been added to the README.md

https://github.com/MeetMe/PaletteBar/commit/ec7631b73c1d964c7032423f4adb64dba2183cc2
